#!/usr/bin/env python3
from satbench.script import *
from configparser import ConfigParser

parser = argparse.ArgumentParser()
parser.add_argument("-f", "--foreground", action="store_true")
args = parser.parse_args()

config = ConfigParser()
config.read(root / "env.ini")

start_args = ["-t", config["start"]["threads"], "-m", config["start"]["memory_mb"]]

if args.foreground:
    start_args.append("-f")

cmd("benchrunner", "start", *start_args).run()
